services:
  - type: web
    name: webgis
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn webgis.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: webgis-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://tamrin-webgis.netlify.app

databases:
  - name: webgis-db
    databaseName: webgis
    plan: free
    ipAllowList: []
