# Generated by Django 5.1.2 on 2025-06-10 06:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbkZanjan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('folderpath', models.CharField(max_length=254)),
                ('symbolid', models.BigIntegerField()),
                ('altmode', models.IntegerField()),
                ('base', models.FloatField()),
                ('clamped', models.IntegerField()),
                ('extruded', models.IntegerField()),
                ('snippet', models.CharField(blank=True, max_length=254, null=True)),
                ('popupinfo', models.CharField(blank=True, max_length=254, null=True)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostan_code', models.IntegerField()),
                ('name', models.CharField(max_length=19)),
                ('jameiyat', models.IntegerField()),
                ('tamab_code', models.IntegerField()),
                ('basin_code', models.IntegerField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Hydrometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=27)),
                ('code', models.CharField(max_length=16)),
                ('station', models.CharField(max_length=36)),
                ('river', models.CharField(max_length=31)),
                ('tool', models.CharField(max_length=18)),
                ('longtitude', models.FloatField()),
                ('arz', models.CharField(max_length=18)),
                ('latitude', models.FloatField()),
                ('height', models.FloatField()),
                ('data_from', models.FloatField()),
                ('degree', models.FloatField()),
                ('mahdode_co', models.FloatField()),
                ('mahdode_na', models.CharField(max_length=34)),
                ('hoze30_cod', models.FloatField()),
                ('hoze30_nam', models.CharField(max_length=40)),
                ('hoze6_code', models.FloatField()),
                ('hoze6_name', models.CharField(max_length=32)),
                ('areakm2', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drainiran', models.CharField(max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='StudyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perimeter', models.FloatField()),
                ('area', models.FloatField()),
                ('os_moteval', models.CharField(max_length=30)),
                ('mah_code', models.FloatField()),
                ('mah_name', models.CharField(max_length=38)),
                ('hoze30code', models.IntegerField()),
                ('hoze30name', models.CharField(max_length=37)),
                ('hoze6code', models.IntegerField()),
                ('hoze6name', models.CharField(max_length=32)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
