# Generated by Django 5.1.2 on 2025-06-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='drainiran',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
