# Generated by Django 5.1.2 on 2025-05-15 08:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbkZanjan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('folderpath', models.CharField(max_length=254)),
                ('symbolid', models.BigIntegerField()),
                ('altmode', models.IntegerField()),
                ('base', models.FloatField()),
                ('clamped', models.IntegerField()),
                ('extruded', models.IntegerField()),
                ('snippet', models.CharField(max_length=254)),
                ('popupinfo', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('ostan_code', models.IntegerField()),
                ('name', models.CharField(max_length=17)),
                ('jameiyat', models.BigIntegerField()),
                ('tamab_code', models.IntegerField()),
                ('basin_code', models.IntegerField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Hydrometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.FloatField()),
                ('rank_of_pr', models.FloatField()),
                ('province', models.CharField(max_length=254)),
                ('code', models.CharField(max_length=254)),
                ('station', models.CharField(max_length=254)),
                ('river', models.CharField(max_length=254)),
                ('tool', models.CharField(max_length=254)),
                ('longtitude', models.FloatField()),
                ('arz', models.CharField(max_length=254)),
                ('latitude', models.FloatField()),
                ('height', models.FloatField()),
                ('data_from', models.FloatField()),
                ('degree', models.FloatField()),
                ('mahdode_co', models.FloatField()),
                ('mahdode_na', models.CharField(max_length=254)),
                ('hoze30_cod', models.FloatField()),
                ('hoze30_nam', models.CharField(max_length=254)),
                ('hoze6_code', models.FloatField()),
                ('hoze6_name', models.CharField(max_length=254)),
                ('mahdodeh_t', models.CharField(max_length=50)),
                ('hozeh30_t', models.CharField(max_length=50)),
                ('hozeh6_t', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=5, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
