# Generated by Django 5.1.2 on 2025-05-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_abkzanjan_city_hydrometry_river_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abkzanjan',
            name='popupinfo',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='abkzanjan',
            name='snippet',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
