# Generated by Django 5.1.2 on 2025-06-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_abkzanjan_popupinfo_alter_abkzanjan_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abkzanjan',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
