# Generated by Django 5.1.2 on 2025-06-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_abkzanjan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abkzanjan',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
